# Generated by Django 3.1.1 on 2020-10-04 20:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDisciplineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'User Discipline Types',
            },
        ),
        migrations.CreateModel(
            name='UserDisciplineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for this model entry (also primary key)', primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_guild_snowflake', models.BigIntegerField(help_text='The Discord Snowflake of the guild this event is related to', verbose_name='Discord Guild Snowflake')),
                ('discord_user_snowflake', models.BigIntegerField(help_text='the Discord snowflake of the user discipline by this instance', verbose_name='Disciplined Discord User Snowflake')),
                ('discipline_content', models.CharField(blank=True, help_text='The discipline data content, if any', max_length=256, verbose_name='Discipline Content')),
                ('username_when_disciplined', models.CharField(help_text='The username of the user at the time of the issuance of this discipline', max_length=256, verbose_name='Username When Disciplined')),
                ('moderator_user_snowflake', models.BigIntegerField(help_text='The Discord snowflake of the moderator performing the discipline', verbose_name='Moderator Discord User Snowflake')),
                ('reason_for_discipline', models.TextField(help_text='The reason for this discipline instance', verbose_name='Reason for Discipline')),
                ('discipline_start_date_time', models.DateTimeField(auto_now_add=True, help_text='The time at which this discipline event was created', verbose_name='Discipline Start Date/Time')),
                ('discipline_end_date_time', models.DateTimeField(blank=True, help_text='The time at which this discipline will be removed automatically; if empty, discipline is permanent', null=True, verbose_name='Discipline End Date/Time')),
                ('is_terminated', models.BooleanField(default=False, help_text='If checked, this discipline was automatically rescinded at the end date.', verbose_name='Is Terminated')),
                ('is_pardoned', models.BooleanField(default=False, help_text='If checked, this user has been pardoned and this discipline is not in effect', verbose_name='Is Pardoned')),
                ('discipline_type', models.ForeignKey(help_text='the type of discipline this instance represents', on_delete=django.db.models.deletion.CASCADE, to='linkus_bot.userdisciplinetype')),
            ],
            options={
                'verbose_name_plural': 'User Discipline Events',
            },
        ),
    ]
