# Generated by Django 3.1.1 on 2020-09-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkus_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdisciplineevent',
            name='discipline_content',
            field=models.CharField(blank=True, help_text='The discipline data content, if any', max_length=256, verbose_name='Discipline Content'),
        ),
    ]
