# Generated by Django 3.1.3 on 2020-11-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineSubConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_channel_snowflake', models.BigIntegerField(help_text='The snowflake of the channel for moderation commands', verbose_name='Moderation Channel Snowflake')),
                ('moderation_role_snowflake', models.BigIntegerField(help_text='The role required for moderation commands to be used', verbose_name='Moderation Role Snowflake')),
                ('moderation_channel_only', models.BooleanField(default=True, help_text='If True, commands will only function in the moderation channel, regardless of user role', verbose_name='Moderation Channel Only')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionSubConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_description_line', models.CharField(help_text='The default line that will be used with emote mappings; can include {emoji} and {role}', max_length=64, verbose_name='Default Description Line')),
                ('allow_unmapped_reactions', models.BooleanField(help_text='if True, we allow unmapped emotes to remain as reactions on the reaction role embed', verbose_name='Allow Unmapped Reactions')),
                ('allow_multiple_emotes_per_role', models.BooleanField(default=False, help_text='If True, multiple emotes can map to the same role on a reaction role embed', verbose_name='Allow Multiple Emotes Per Role')),
                ('allow_multiple_roles_per_emote', models.BooleanField(default=False, help_text='If True, a single emote can map to multiple roles on a reaction role embed', verbose_name='Allow Multiple Roles Per Emote')),
                ('remove_roles_on_react_remove', models.BooleanField(default=False, help_text='If True, remove the corresponding role from all that have it if the emoji mapping is removed', verbose_name='Remove Roles on React Remove')),
            ],
        ),
        migrations.CreateModel(
            name='BotGuildConfiguration',
            fields=[
                ('guild_snowflake', models.BigIntegerField(help_text='The unique Guild that this configuration is for', primary_key=True, serialize=False, verbose_name='Guild Snowflake')),
                ('logging_channel_snowflake', models.BigIntegerField(help_text='The channel that errors and feedback messages will be logged to', verbose_name='Logging Channel Snowflake')),
                ('discipline_configuration', models.OneToOneField(help_text='The discipline sub-configuration for this guild configuration', on_delete=django.db.models.deletion.CASCADE, to='bot_configuration.disciplinesubconfiguration', verbose_name='Discipline Configuration')),
                ('reaction_configuration', models.OneToOneField(help_text='The reaction roles sub-configuration for this guild configuration', on_delete=django.db.models.deletion.CASCADE, to='bot_configuration.reactionsubconfiguration', verbose_name='Reaction Configuration')),
            ],
        ),
    ]
