# Generated by Django 3.1.1 on 2020-10-28 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedReactionRoleEmbed',
            fields=[
                ('message_snowflake', models.BigIntegerField(help_text='The discord snowflake for the tracked reaction roles embed', primary_key=True, serialize=False, verbose_name='Message Snowflake')),
                ('creating_member_snowflake', models.BigIntegerField(help_text='The discord snowflake of the user that created this instance', verbose_name='Creating Member Snowflake')),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='The date/time this entry was created', verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionRoleEmojiMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_snowflake', models.BigIntegerField(help_text='The snowflake of the role for this mapping entry', verbose_name='Role Snowflake')),
                ('emoji_snowflake', models.BigIntegerField(help_text='The snowflake of the emoji for this mapping entry', verbose_name='Emoji Snowflake')),
                ('tracked_embed', models.ForeignKey(help_text='The reaction role embed this mapping is relevant for', on_delete=django.db.models.deletion.CASCADE, related_name='role_emoji_mappings', to='reaction_roles.trackedreactionroleembed', verbose_name='Tracked Embed')),
            ],
        ),
    ]
