# Generated by Django 3.1.3 on 2020-11-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionRoleEmojiMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_snowflake', models.BigIntegerField(help_text='The snowflake of the emoji for this mapping entry', verbose_name='Emoji Snowflake')),
                ('role_snowflake', models.BigIntegerField(help_text='The snowflake of the role for this mapping entry', verbose_name='Role Snowflake')),
            ],
            options={
                'verbose_name_plural': 'Reaction Role Emoji Mappings',
            },
        ),
        migrations.CreateModel(
            name='TrackedReactionRoleEmbed',
            fields=[
                ('message_snowflake', models.BigIntegerField(help_text='The discord snowflake for the tracked reaction roles embed', primary_key=True, serialize=False, verbose_name='Message Snowflake')),
                ('guild_snowflake', models.BigIntegerField(help_text='The guild within which this reaction role embed exists', verbose_name='Guild Snowflake')),
                ('alias', models.CharField(help_text='A human readable alias for this reaction role embed', max_length=64, verbose_name='Alias')),
                ('creating_member_snowflake', models.BigIntegerField(help_text='The discord snowflake of the user that created this instance', verbose_name='Creating Member Snowflake')),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='The date/time this entry was created', verbose_name='Creation Time')),
            ],
            options={
                'verbose_name_plural': 'Tracked Reaction Role Embeds',
            },
        ),
        migrations.AddConstraint(
            model_name='trackedreactionroleembed',
            constraint=models.UniqueConstraint(fields=('guild_snowflake', 'alias'), name='unique_alias'),
        ),
        migrations.AddField(
            model_name='reactionroleemojimapping',
            name='tracked_embed',
            field=models.ForeignKey(help_text='The reaction role embed this mapping is relevant for', on_delete=django.db.models.deletion.CASCADE, related_name='role_emoji_mappings', to='reaction_roles.trackedreactionroleembed', verbose_name='Tracked Embed'),
        ),
    ]
