# Generated by Django 3.1.1 on 2020-11-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedreactionroleembed',
            name='guild_snowflake',
            field=models.BigIntegerField(default=1, help_text='The guild within which this reaction role embed exists', verbose_name='Guild Snowflake'),
            preserve_default=False,
        ),
    ]
