# Generated by Django 3.1.3 on 2020-11-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction_roles', '0003_auto_20201128_2049'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trackedreactionroleembed',
            name='unique_alias',
        ),
        migrations.AddConstraint(
            model_name='trackedreactionroleembed',
            constraint=models.UniqueConstraint(fields=('guild_snowflake', 'alias'), name='unique_alias'),
        ),
    ]
